from django.conf.urls import url
from .views import \
    (BusinessAccountDashboard,
     BusinessProfileCreateView,
     BusinessProfileUpdateView,
     BusinessProfileDetailView,
     CreditCardInfoCreateView,
     CreditCardInfoUpdateView,
     LocationTimeCreateView,
     LocationTimeUpdateView,
     LocationTimeDetailView,
     LocationCreateView,
     LocationUpdateView,
     LocationDeleteView,
     Support,
     Settings,
     Faq,
     Billing,
     CreditCard,
     Appoval,
     Locations)

urlpatterns = [
    url(r'^businessdashboard/', BusinessAccountDashboard.as_view(), name='business_dashboard'),
    url(r'^profile/', BusinessProfileDetailView, name='business_profile'),
    url(r'^settings/', Settings, name='settings'),
    url(r'^locations/', Locations, name='locations'),
    url(r'^approval/', Appoval, name='approval'),
    url(r'^billing/', Billing, name='billing'),
    url(r'^creditcard/', CreditCard, name='creditcard'),
    url(r'^faq/', Faq, name='faq'),
    url(r'^support/', Support, name='support'),
    url(r'^locationtime/', LocationTimeDetailView, name='location_time'),
    url(r'^locationtimecreate/', LocationTimeCreateView.as_view(), name='location_time_create'),
    url(r'^locationtimeupdate/(?P<id>[\w-]+)/$', LocationTimeUpdateView.as_view(), name='location_time_update'),
    url(r'^businesscreditcardcreate/', CreditCardInfoCreateView, name='business_creditcard_create'),
    url(r'^businesscreditcardupdate/(?P<id>[\w-]+)/$', CreditCardInfoUpdateView, name='business_creditcard_update'),
    url(r'^businessprofilecreate/', BusinessProfileCreateView.as_view(), name='business_profile_create'),
    url(r'^businessprofileupdate/(?P<slug>[\w-]+)/$', BusinessProfileUpdateView.as_view(), name='business_profile_update'),
    url(r'^businesslocationcreate/', LocationCreateView.as_view(), name='business_location_create'),
    url(r'^businesslocationupdate/(?P<slug>[\w-]+)/$', LocationUpdateView.as_view(), name='business_location_update'),
    url(r'^businesslocationdelete/(?P<slug>[\w-]+)/$', LocationDeleteView.as_view(), name='business_location_delete'),

]